# HAIT第二回 補足教材
### テーマ：Numpy, Pandas練習

# 1) Numpyの基本的なメソッドの補足  
 **目的**   
Numpyの基本的なメソッドの復習、整理する  
  
  
ここでは、Numpyの便利な機能について扱っていきます。小問を解く過程で復習していきましょう。

In [7]:
# 基本的なはモジュールのインポート
import numpy as np
import pandas as pd

### Ex1-1.arange関数を使用して、10から44までのarrayを作ってください。

In [8]:
#答え
np.arange(10,45)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

### Ex1-2.上記のarrayの5番目の数字をインデックス指定して取り出してください。

In [9]:
#答え
a = np.arange(10,45)
a[4]

14

### Ex1-3.上記のarrayをデータフレームに変換してください。

In [10]:
#答え
pd.DataFrame(a)

0
0   10
1   11
2   12
3   13
4   14
5   15
6   16
7   17
8   18
9   19
10  20
11  21
12  22
13  23
14  24
15  25
16  26
17  27
18  28
19  29
20  30
21  31
22  32
23  33
24  34
25  35
26  36
27  37
28  38
29  39
30  40
31  41
32  42
33  43
34  44

### Ex1-4.上記のarrayの平均を出して下さい。

In [6]:
#答え
np.mean(a)

27.0

### Ex1-5.上記のarrayを7行5列の2次元配列に変換してください。

In [7]:
#答え
a.reshape(7, 5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

** **

### (参考資料)
以下では実際にデータを分析する際に有用な**1次元配列への変換、def文、for文、if文、hstack関数、vstack関数**を取り扱います。

### Ex1-6.上記のndarrayを一次元配列に変換してください。

In [12]:
#答え
a.reshape((1, -1))[0]
a.reshape(-1,)
np.ravel(a)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

In [13]:
b = a.reshape((1, -1))[0]

#a.reshape((1,-1))は、配列aの行数を1行だけにして列数は要素数に合わせて整形する。(これが-1の意味)
#ただa.reshape((1, -1))では二重リスト(リストの中の要素がリスト、二次元配列)のままなので、これを一次元配列にするために[0]を指定する。

### Ex1-7.def文を使用して偶数の数を数える関数を定義してください

In [15]:
#答え
def counting_even_number(array):
    count = 0
    
    for i in range(len(array)):
        if array[i] % 2 == 0:
            count += 1
        else:
            count += 0
    print("偶数の数は、{}個です。".format(count))

In [16]:
counting_even_number(b)

偶数の数は、18個です。


### Ex1-8.下記のXとYをhstack関数とvstack関数を使用して結合してください。

最後に、教材では触れられていないですが、実際にデータを分析するにあたって便利な**hstack関数**、**vstack関数**を紹介します。

**hstack関数**は**Numpy配列同士を横方向に結合します。** **np.hstack((a, b))**の形で使用することが可能です。(horizontal)

**vstack関数**は**Numpy配列同士を縦方向に結合します。**　**np.vstack((a, b))**の形で使用することが可能です。(vertical)

In [17]:
X =  np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([[10,20,30], [40,50,60], [70,80,90]])

In [18]:
# 答え
np.hstack((X, Y))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])

In [19]:
np.vstack((X, Y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

hstackl関数、vstack関数の詳しい使い方については、以下のサイトを参照してください。
### http://ailaby.com/vstack_hstack/

Numpy同士の結合に関して

___

# 2) Pandasの練習

 **目的**  
自分でDataFrameを作成し、DataFrameから求めるデータを自分自身で取り出すことができるようにする。

In [21]:
# まずはモジュールのインポート
import pandas as pd
import matplotlib as pb

### Ex2.1.  以下の図と同じようなデータフレームを作成しましょう
**教材復習**
<font color="Red">pandasのDataFrameは pd.DataFrame を使ってPythonのリストなどを値とするディクショナリから生成できます。</font>  
  
中身は**辞書形式**で指定すると良いでしょう
<img src="https://s3-ap-northeast-1.amazonaws.com/ai-std/vol2-01.png" width=60%>

In [54]:
#答え
data= pd.DataFrame({"国":["ロシア", "サウジアラビア", "エジプト", "ウルグアイ", "ポルトガル", "スペイン"],
             "地域": ["ヨーロッパ", "アジア", "アフリカ", "南アメリカ", "ヨーロッパ", "ヨーロッパ"],
             "グループ": ["A", "A", "A", "A", "B", "B"],
             "FIFAランキング": [65, 63, 31, 21, 3, 6]
                  })
data

FIFAランキング グループ        国     地域
0         65    A      ロシア  ヨーロッパ
1         63    A  サウジアラビア    アジア
2         31    A     エジプト   アフリカ
3         21    A    ウルグアイ  南アメリカ
4          3    B    ポルトガル  ヨーロッパ
5          6    B     スペイン  ヨーロッパ

### Ex2.2.  上記のデータフレームをarrayに変換してみましょう。
arrayへの変換には、**np.array(dataframe)**を用いると良いでしょう。

In [55]:
#答え
np.array(data)

array([[65, 'A', 'ロシア', 'ヨーロッパ'],
       [63, 'A', 'サウジアラビア', 'アジア'],
       [31, 'A', 'エジプト', 'アフリカ'],
       [21, 'A', 'ウルグアイ', '南アメリカ'],
       [3, 'B', 'ポルトガル', 'ヨーロッパ'],
       [6, 'B', 'スペイン', 'ヨーロッパ']], dtype=object)

### Ex2.3. データフレームの特徴量名のみを抽出しましょう  
rank.columnsに特徴量名(カラム名)が収容されているので実際に見てみましょう

In [56]:
#答え
data.columns

Index(['FIFAランキング', 'グループ', '国', '地域'], dtype='object')

### Ex2.4. 上記のDataFrameが何行何列なのか確認してみましょう
特徴量やデータの数が多くなると全体を概観するのは難しくなります。 
**.shape**を使ってみましょう


In [57]:
#答え
data.shape

(6, 4)

### Ex2-5. 特徴量名についてすべて日本語となっているので英語に書き換えてみましょう。  
FIFAランキング→Ranking  
グループ→Group  
国→Country  
地域→Region

In [58]:
#答え
data.columns = ["Ranking", "Group", "Country", "Region"]
data

Ranking Group  Country Region
0       65     A      ロシア  ヨーロッパ
1       63     A  サウジアラビア    アジア
2       31     A     エジプト   アフリカ
3       21     A    ウルグアイ  南アメリカ
4        3     B    ポルトガル  ヨーロッパ
5        6     B     スペイン  ヨーロッパ

### Ex2-6. 列を書き換えましょう
地域について数字で参照できるようにしましょう。  
この過程はMachine Learningの「欠損値処理とエンコーディング」で学ぶ**マッピング**と同じですが、ここでは愚直に対応する番号をリストで指定しましょう。  
ヨーロッパ：1  
アジア：2  
アフリカ：3    
南アメリカ：4  
とそれぞれ対応させましょう。

In [59]:
#答え
data['Region']=['1','2','3','4','1','1']
data

Ranking Group  Country Region
0       65     A      ロシア      1
1       63     A  サウジアラビア      2
2       31     A     エジプト      3
3       21     A    ウルグアイ      4
4        3     B    ポルトガル      1
5        6     B     スペイン      1

pandas.DataFrameの行名・列名の変更については下記のサイトを参考にしてください。
### https://note.nkmk.me/python-pandas-dataframe-rename/  
       pandas.DataFrameの行名・列名の変更

---
#### ここで、特定の列や行を取得するための手法を練習問題を通して学びましょう。

下記のサイトは、DataFrameの行・列を取り出す方法が分かりやすく載っていますので参考にして以下の問題を解いてみましょう。  

### http://akiyoko.hatenablog.jp/entry/2017/04/03/081630  
      pandas.DataFrame の列の抽出（射影）および行の抽出（選択）方法まとめ
### https://goo.gl/tFNvfu
      Pandas でデータフレームから特定の行・列を取得する


### Ex2-7. Countryについてのデータのみ取り出してください。  
**データ名[参照したいカラム名や条件式]**で参照できます。  
**[]内の条件をみたすようなデータ**が選択されます。

In [60]:
#答え
data['Country']

0        ロシア
1    サウジアラビア
2       エジプト
3      ウルグアイ
4      ポルトガル
5       スペイン
Name: Country, dtype: object

### Ex2-8. Regionが1となっているデータのみ取り出してください

In [61]:
data[data.Region=='1']

Ranking Group Country Region
0       65     A     ロシア      1
4        3     B   ポルトガル      1
5        6     B    スペイン      1

### Ex2-9. GroupとRegionのデータを取り出してください。 
**iloc[]**を用いれば行と列を指定してデータを取り出すことができます。  
**loc[]**を用いればラベル名で指定できます。  
**ix()** なら、ラベル名と数値のいずれでも利用することができます。  
  
**教材復習**  
2.2 スライスでDataFrameを参照する　を見てみましょう

In [62]:
#答え
data.iloc[:, [1,3]]

Group Region
0     A      1
1     A      2
2     A      3
3     A      4
4     B      1
5     B      1

In [69]:
#答え
data.loc[:, ["Group","Region"]]

Group Region
0     A      1
1     A      2
2     A      3
3     A      4
4     B      1
5     B      1

In [73]:
#答え
data.ix[:,['Group','Region']]

Group Region
0     A      1
1     A      2
2     A      3
3     A      4
4     B      1
5     B      1

In [75]:
#答え
data.ix[:,[1,3]]

Group Region
0     A      1
1     A      2
2     A      3
3     A      4
4     B      1
5     B      1

### Ex2-10.   **Ex2-7とEx2-9で取り出したデータをつなげましょう**  
  
Countryについて取り出したデータをdf1,GroupとRegionを取り出したデータをdf2とします。これらを結合するにはどうすればよいでしょうか。  
結合については**pd.concat([,],axis=1)**を用いると良いでしょう。  
**データ連結処理**については以下のサイトを参考にしてみてください
### http://sinhrks.hatenablog.com/entry/2015/01/28/073327

In [78]:
#答え
df1=data['Country']
df2=data.iloc[:, [1,3]]
df=pd.concat([df1,df2],axis=1)
df

Country Group Region
0      ロシア     A      1
1  サウジアラビア     A      2
2     エジプト     A      3
3    ウルグアイ     A      4
4    ポルトガル     B      1
5     スペイン     B      1

** **

### (参考資料)
以下では教材では触れられていないものの、実際にデータを分析する際に便利な関数を学んでいきます。  
各自家で目を通してみてください。

ここで扱うのは、**sort関数、groupby関数、merge関数**の３つです。

### Ex2-11. Regionを軸にデータフレームを値の大きい順に並び替えてみましょう。

データの並び替えには、**sort関数**を用いると良いでしょう。

**sort関数**は、特定の特徴量に注目して並び替えることが可能です。

昇順の場合は**.sort_values(by='特定の特徴量')**、降順の場合は**.sort_values(by='特定の特徴量', ascending=False)**の形で使用できます。

In [79]:
#答え
data.sort_values(by="Region", ascending=False)

Ranking Group  Country Region
3       21     A    ウルグアイ      4
2       31     A     エジプト      3
1       63     A  サウジアラビア      2
0       65     A      ロシア      1
4        3     B    ポルトガル      1
5        6     B     スペイン      1


データフレームのソートについては以下のサイトを参考にしてみてください。
##### https://pythondatascience.plavox.info/pandas/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%82%92%E3%82%BD%E3%83%BC%E3%83%88%E3%81%99%E3%82%8B

### Ex.2-12. 以下のデータフレームにおける地域ごとのランキング平均を求めてください。

特定の変数を軸にデータを集計する際には、**groupby関数**が便利です。

**.groupby("特定の変数")**の形で使用することができます。ただし、groupbyはあくまで指定された変数ごとにまとめる機能なので、その後にmeanやmin, max, sumなどの別の関数を働かせる必要があります。

例) Aという変数のまとまりのなかでのBの最小値を取り出したい時　⇨　dataframe.groupby("A")["B"].min()

In [45]:
#答え
df_new = data.groupby("Region",as_index=False)["Ranking"].mean()
df_new

Region    Ranking
0      1  24.666667
1      2  63.000000
2      3  31.000000
3      4  21.000000


groupby関数の詳細な使い方については以下のサイトを参照してください。
### http://ailaby.com/groupby_easy/

### Ex.2-13.これまでに作成されたdataに次に提示するdata2を繋げてdata2の国のデータのみを取り出してください。

一部の要素が共通しているデータフレーム同士を結合する際には、**merge関数**が非常に有用です。
**merge関数**は、データフレーム同士の内部結合や外部結合を行うことができます。
**pd.merge(dataframe1, dataframe2, on 起点となる変数)**の形で使用できます。ここでは、**内部結合**のみ扱います。

In [46]:
data

Ranking Group  Country Region
0       65     A      ロシア      1
1       63     A  サウジアラビア      2
2       31     A     エジプト      3
3       21     A    ウルグアイ      4
4        3     B    ポルトガル      1
5        6     B     スペイン      1

In [47]:
data2= pd.DataFrame({"Country":["ロシア", "サウジアラビア", "ウルグアイ", "スペイン"],
                    "Population(億)": [1.443, 0.3228, 0.0344, 0.4656],
                    "Height(cm)":[184.3, 176.2,170.0,173.1]
                   })
data2

Country  Height(cm)  Population(億)
0      ロシア       184.3         1.4430
1  サウジアラビア       176.2         0.3228
2    ウルグアイ       170.0         0.0344
3     スペイン       173.1         0.4656

In [48]:
#答え
data3 = pd.merge(data, data2, on="Country")
data3

Ranking Group  Country Region  Height(cm)  Population(億)
0       65     A      ロシア      1       184.3         1.4430
1       63     A  サウジアラビア      2       176.2         0.3228
2       21     A    ウルグアイ      4       170.0         0.0344
3        6     B     スペイン      1       173.1         0.4656


merge関数の詳細な使い方については以下のサイトを参照してください。
### http://sinhrks.hatenablog.com/entry/2015/01/28/073327

** **

＊内部結合  
    異なるデータフレームを結合させて、結合可能なデータのみを取り出すこと。

＊外部結合  
    一方のデータを残して、もう一方のデータを可能な範囲で結合させて取り出すこと。  
                        左外部結合、右外部結合、完全外部結合の3種類がある。


ちょっと分かりにくいと思うので、こちらのサイトも参照してください。
http://wa3.i-3-i.info/word1263.html

### お疲れ様でした